### ISSUE TITLE
set Output Format

### ISSUE THREAD

**Issue by Doomsta** [jacobmarshall/pokevision-cli#12]
It would be awesome to set the output format. 
**Example:**
`pokevision watch 
  --lat=40.712774   
  --lon=-74.013408 
  --name="World Trade Center" 
  --format "%POKEMON% %LAT%,%LON%"
` 
This make it possible to pipe the output.

**Comment by jmshal** [comment]
Great suggestion, that can absolutely be accomplished. I will see about getting this into 1.0.8.

**Comment by jmshal** [comment]
I know I said this would be in 1.0.8, but 1.0.8 as well as 1.0.9 included some critical bugfixes. I will see about getting this into the next full release 😄

**Comment by jmshal** [comment]
This just shipped in [1.0.10](https://github.com/jacobmarshall/pokevision-cli/releases/tag/1.0.10) - check out [advanced usage](https://github.com/jacobmarshall/pokevision-cli/blob/master/docs/advanced-usage.md#formatting-output---format) for more info.

**Comment by jmshal** [comment]
The actual syntax for your example would be `--format="{{.Name}} {{.Latitude}},{{.Longitude}}"`.
