### ISSUE TITLE
Expires in 8 Hours?

### ISSUE THREAD

**Issue by solteranis** [jacobmarshall/pokevision-cli#17]
Hello,

I was wondering why every pokemon shows that it expires in 8Hours? is this a bug or expected results?

**Comment by jmshal** [comment]
That's rather odd. I've not seen that issue before.

What version of pokevision-cli are you using?
Which OS are you running?

**Comment by solteranis** [comment]
Running version 1.0.8, on centos 6.8. Running the command as follows:

pokevision watch --forever \
--lat=NUM \
--lon=NUM \
--name="NAME" \
--slack --slack-webhook-url="URL" \
--slack-channel=CHANNEL &

Here is an example of the output I get:

Paras (https://maps.google.com/maps?q=LONG,LAT=19)
298m away from NAME
Expires in 8 hours

**Comment by jmshal** [comment]
Interesting. If you don't mind, could you send me the coordinates to git@jacobmarshall.co (just so it's private) to see whether I see the same output from where I am. The tool hasn't been specifically tested with CentOS, but I see no reason it should be outputting any differently for you.

**Comment by solteranis** [comment]
Just sent. Let me know if you need anything else

**Comment by jmshal** [comment]
Thanks for that. I see all the correct times. I wonder, however, that maybe it's due to the timezone you're in. I will do some more tests and see whether the time rendering/comparing needs tweaking to UTC for consistency.

**Comment by solteranis** [comment]
Thanks for the help @jacobmarshall! keep up the great work

**Comment by jmshal** [comment]
Having said that. I live in New Zealand, and I've not had any issues. I find it unlikely it's purely timezone related. Have you got your local clock set correctly on your system?

**Comment by solteranis** [comment]
I'll do some checking on my end. I'm doing a system update atm as well. I'll post back once the update is done

**Comment by jmshal** [comment]
Sweet, thanks :+1:

**Comment by solteranis** [comment]
system update just finished, but it was an issue with the configured NTP servers. I reconfigured the file and I've got accurate times now.

**Comment by jmshal** [comment]
Great, glad it's working now :)
