### ISSUE TITLE
Notifying Bugsnag Error - Kills Process

### ISSUE THREAD

**Issue by OutlandishMatt** [jacobmarshall/pokevision-cli#18]
I'm running the pokevision.exe off Windows 10, version 1.0.10. After a certain amount of time, usually 10-15 minutes the process will end with the following error:

2016/07/30 00:54:46 notifying bugsnag: Unknown server error
2016/07/30 00:54:46 Unknown server error

**Comment by jmshal** [comment]
Add the `--forever` flag, to ignore those kinds of errors.

**Comment by OutlandishMatt** [comment]
I did but didn't know if you needed to know about it. Thank you.

**Comment by jmshal** [comment]
Are you saying you still have the issue even when using `--forever`?

**Comment by OutlandishMatt** [comment]
No, I'm saying prior to reading about the advanced features I was getting it. I didn't know if you needed to know about the error or not since I didn't see it listed in here. I've now added the forever tag and no longer receiving it. Thank you.

**Comment by jmshal** [comment]
Ah ok 👍
