### ISSUE TITLE
Format tag output to equal lat/lon coordinates?

### ISSUE THREAD

**Issue by OutlandishMatt** [jacobmarshall/pokevision-cli#19]
Is it possible to have the format tell you the exact latitude and longitude of the pokemon that spawns? From what I understand spawn points are on a timer and I would like to compile loot tables for spawn points in my area.

**Comment by jmshal** [comment]
Not entirely sure what you mean to be honest. The `--format` flag already has the ability to extract the latitude & longitude of a spawn.

Example:

```
--format="{{.Name}} {{.Latitude}} {{.Longitude}}"
```

Output:

```
Omanyte 40.709493430375 -74.015644418091
Pidgey 40.71078075392 -74.015460796626
Poliwag 40.711362051933 -74.01683795331
Krabby 40.713112086938 -74.016103470981
Exeggcute 40.713912113383 -74.017388813203
Goldeen 40.715275834018 -74.016654332993
Venonat 40.715327078172 -74.016470712499
Ekans 40.715415022373 -74.014909931171
Meowth 40.708820308455 -74.013073701515
Oddish 40.709980676046 -74.014175441427
Pidgey 40.70908876049 -74.011696517691
Kakuna 40.709100984382 -74.011237454211
Bellsprout 40.709267715427 -74.010778389628
Rattata 40.709782481151 -74.010594763486
Staryu 40.70988416719 -74.009676630131
Spearow 40.713661207669 -74.012890077579
Goldeen 40.711519476395 -74.009768443665
Exeggcute 40.711699994697 -74.009952070601
Pidgeotto 40.712460289301 -74.010411137168
Zubat 40.712588774601 -74.010227510673
Fearow 40.712640009216 -74.010043884002
Goldeen 40.712636796708 -74.007840350193
Poliwag 40.713692258462 -74.00765672123
Psyduck 40.715181727247 -74.013808195495
Nidoran♀ 40.716019218693 -74.014267252799
Caterpie 40.716919378467 -74.013532760584
Spearow 40.714801360198 -74.008942120272
Zubat 40.714929025755 -74.008207607592
```

Is that what you mean, or am I confusing something?

**Comment by jmshal** [comment]
https://github.com/jacobmarshall/pokevision-cli/blob/master/docs/advanced-usage.md#formatting-output---format

**Comment by OutlandishMatt** [comment]
That's what I mean, yes. I figured it out after I posted it but what is the expiring time reference? I thought it would be .Time but if I'm looking at the PokemonMeta it's actually time.Time which I can't reference. Also, is there no way to make it spit out the Lat and Lon in Slack? I tried to change the name but --name="{{.Latitude}},{{.Longitude}}" did not work nor did it without quotes.

I wouldn't mind seeing "Expires in", "Location", "Distance", and "Latitude,Longitude" be displayed in slack. I think it would definitely help us watch spawn points.

Also, thank you for all your help. Really appreciate it.

**Comment by jmshal** [comment]
I'll definitely consider making it possible to customise the slack integration, for sure. It won't be as customisable as the `--format` flag, but it will likely serve your purpose.

By the way, clicking on the Pokémon's name in Slack will take you to Google Maps with a pin dropped at it's location.

The `--format` field name for the expiration time is `{{.ExpiresAt}}` or `{{.ExpiresAtTimestamp}}` for the unix timestamp.

Hope that helps.

**Comment by OutlandishMatt** [comment]
Thank you. I greatly appreciate this program and your help.

**Comment by jmshal** [comment]
You're most welcome 😄
