### ISSUE TITLE
hi sir

### ISSUE THREAD

**Issue by KiriharaSenpai** [jacobmarshall/pokevision-cli#4]
Hi sir have a good day thanks for your works i want to ask a question how can i run pokevision.exe when i click it nothing happening

**Comment by jmshal** [comment]
Hey @KiriharaSenpai, the tool is meant to be run from the CLI. So you'll need to open up cmd.exe or Powershell and call the .exe like so...

```
pokevision.exe watch --lat=XXX --lon=XXX --name=Home --range=300 --forever
```

Which would notify you when there are new Pokémon 300 meters around your coordinates.

**Comment by KiriharaSenpai** [comment]
thank you for your answer i did everthing you told me to do
but got this error http://imgur.com/a/7nESd

**Comment by KiriharaSenpai** [comment]
oh pokevision is down at the moment gonna try it again once it come back again
