### ISSUE TITLE
multilanguage support

### ISSUE THREAD

**Issue by ghost** [jacobmarshall/pokevision-cli#5]
Hi,

i was born and grown up in germany so english itself is not the problem.  But i dont know what a "Charmander" is but a "Glumanda" is deep in my mind ^^

Could u maybe add support for pokemon-names in other languages? (Only the names, all other outputs could be english)

https://github.com/AHAAAAAAA/PokemonGo-Map/tree/master/static/locales
(Just as example)

Greetings :)

**Comment by jmshal** [comment]
Absolutely. I'm sorry I didn't even think of that aspect. I will place this at the top of the todo list, because I am sure it will come up a lot.

Thanks!

**Comment by jmshal** [comment]
This has just landed in [1.0.6-rc.2](https://github.com/jacobmarshall/pokevision-cli/releases/tag/1.0.6-rc.2).

Just add `--locale=de` to the command.

**Comment by ghost** [comment]
Thank u :)

What u think about autodetect the lanuage?

https://blog.golang.org/matchlang

So no command would needed (except u would overwrite it)

**Comment by jmshal** [comment]
I'll be sure to slip this into 1.0.7 for you :)

**Comment by ghost** [comment]
thank u^^

**Comment by jmshal** [comment]
Now available (in preview) in [1.0.7-rc.2](https://github.com/jacobmarshall/pokevision-cli/releases/tag/1.0.7-rc.2). Enjoy 😜

<img width="873" alt="screenshot 2016-07-29 19 23 42" src="https://cloud.githubusercontent.com/assets/4710291/17240861/0be4912e-55c2-11e6-985b-a6630d97ffd2.png">
