### ISSUE TITLE
Windows 10 Toast Notification

### ISSUE THREAD

**Issue by ghost** [jacobmarshall/pokevision-cli#6]
Donno if its possible in GO. But a Windows 10 Notification would be insane.

I only found this Powershell example:

https://gist.github.com/altrive/72594b8427b2fff16431

**Comment by jmshal** [comment]
It's absolutely my intention to get Windows 10 desktop notifications working. I suspect I'll release 1.0.6 without it, just so people can use it (at least on Mac OS X). And Windows 10 support will follow soon after.

**Comment by jmshal** [comment]
I forgot to update this issue - Windows 10 toast notifications landed a few versions ago :)
