### ISSUE TITLE
How do I push updates to a slack channel?

### ISSUE THREAD

**Issue by weigel23** [jacobmarshall/pokevision-cli#7]

**Comment by jmshal** [comment]
Use the --slack --slack-webhook-url and --slack-channel flags.

**Comment by ketra** [comment]
to pitch in on this, i have the same Question/bug(maybe),

cause i have added the above stated settings, but nothing is apearing in my slack.

**Comment by weigel23** [comment]
pokevision.com doesn't work for me at the moment either. Maybe that's why.

**Comment by ketra** [comment]
true, but this morning i had 25 messages in console and nothing in slack.

**Comment by jmshal** [comment]
Just as a follow up;
- The `--slack` flag enables Slack notifications.
- The `--slack-webhook-url` is where you pass your Slack webhook. You have to create an incoming webhook within Slacks admin pages.
- The `--slack-channel` is an optional flag which overrides which channel the bot sends to.

**Comment by ketra** [comment]
thanks for the message, i was being a noob. i put my slack url not a created webhook url in the command. working for me. now :)

**Comment by jmshal** [comment]
Great!
