### ISSUE TITLE
Help running on Ubuntu 32

### ISSUE THREAD

**Issue by jbazalar** [jacobmarshall/pokevision-cli#8]
Ubuntu 16.04 LTS - i686
https://github.com/jacobmarshall/pokevision-cli/releases/download/1.0.6-rc.1/linux-386.tar.gz
Placed file in /usr/local/bin.

jb@myhost:~$ pokevision -v
2016/07/27 15:14:45 OS does not support terminal-notifier
pokevision version 1.0.6-rc.1
jb@myhost:~$ 2016/07/27 15:14:45 OS does not support terminal-notifier

jb@myhost:~$ pokevision watch --lat=34.00846023931052 --lon=-118.49802017211914 --name=Beach
2016/07/27 15:15:26 OS does not support terminal-notifier
2016/07/27 15:15:26 OS does not support terminal-notifier
2016/07/27 15:15:26 notifying bugsnag: open : no such file or directory
2016/07/27 15:15:26 open : no such file or directory

**Comment by jmshal** [comment]
Cheers @jbazalar, I've not yet tested the Linux build of 1.0.6-rc.1.

As of right now, the only difference between 1.0.5 and 1.0.6-rc.1 is desktop notifications, so you should be all good using 1.0.5 for now.

Expect this to be fixed by the next release candidate.

**Comment by jbazalar** [comment]
Ah okay, let me try version 1.0.5.

**Comment by jbazalar** [comment]
@jacobmarshall 1.0.5 worked as expected. Thank you.
