### ISSUE TITLE
Document cli usage

### ISSUE THREAD

**Issue by igormursa-newstore** [jacobmarshall/pokevision-cli#9]
Hello,
First of all I would like to say thank you for what you did,
Now to the question
you have a lot of screen shots but only one usage explained, i saw already that someone asked about the slack, but i didn't see how to use notifications on mac,
it will make things more easier for people if you will provide that

**Comment by jmshal** [comment]
Cheers @igormursa-newstore for your feedback. I'm planning on fully documenting the usage soon. Sorry I have not done this sooner.

As for desktop notifications, simply add `--notify` onto the end of the command.

**Comment by igormursa-newstore** [comment]
Thank you ;)

**Comment by jmshal** [comment]
Check out https://github.com/jacobmarshall/pokevision-cli/blob/master/docs/readme.md for some initial documentation I quickly put together.
